support elevation and time
wondie/batch_gps_importer pull request #14
Opened 2024-12-20 06:49 UTC by SamMeuli

Use appropriate types for:
- elevation (`QVariant.Double`)
- capture_time (`QVariant.DateTime`)

2025-01-11 23:20 UTC, wondie commented
@SamMeuli I switched to your repo and branch but I am not getting any change as compared to the current version. I used this file https://github.com/wondie/batch_gps_importer/files/7138880/samples.zip Which is in #6 

The current master already recognize elevation but not time, the same for your version. Do you have a data that did import elevation using on master and worked on your branch?

2025-01-11 23:46 UTC, wondie requested changes

2025-01-11 23:46 UTC, wondie commented on importer/process_import.py
> +def _create_field_and_value(attribute_name, attribute_value_as_str):
It is better to add it in GpxToFeature class as static method.

2025-01-11 23:46 UTC, wondie commented on importer/process_import.py
> +        field_value = float(attribute_value_as_str)
I got the error below when trying to import all the gpx in the sample data of the plugin. 

```
An error has occurred while executing Python code: 

TypeError: float() argument must be a string or a real number, not 'NoneType' 
Traceback (most recent call last):
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\ui\gps_importer_starter.py", line 563, in accept
    self.process.finish_import(self.param_store)
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 685, in finish_import
    number_of_features = self.combine_features(parm_store)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 655, in combine_features
    feature_list = self.gpx_to_feature_list(parm_store)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 628, in gpx_to_feature_list
    gpx_to_layer.init_gpx_import(gpx_path)
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 196, in init_gpx_import
    self.gpx_to_point_list()
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 226, in gpx_to_point_list
    self.join_points_and_attributes()
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 294, in join_points_and_attributes
    self.create_line()
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 354, in create_line
    self.create_feature(line_geom, list(self.gpx_data.values())[0])
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 407, in create_feature
    qgs_field, value = _create_field_and_value(attr_name, attr_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/andex/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_gps_importer\importer\process_import.py", line 744, in _create_field_and_value
    field_value = float(attribute_value_as_str)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'

```

2025-01-13 07:48 UTC, SamMeuli commented
> @SamMeuli I switched to your repo and branch but I am not getting any change as compared to the current version. I used this file https://github.com/wondie/batch_gps_importer/files/7138880/samples.zip Which is in #6
> 
> The current master already recognize elevation but not time, the same for your version. Do you have a data that did import elevation using on master and worked on your branch?
> 
> Also after fixing the errors below, I still couldn't see any difference between the sample data processed by master and your version. Please see the sample data processed by master below. ![image](https://private-user-images.githubusercontent.com/9709624/402297587-d97c44e3-6ec1-42c1-8906-19464f441a57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NTI2MjgsIm5iZiI6MTczNjc1MjMyOCwicGF0aCI6Ii85NzA5NjI0LzQwMjI5NzU4Ny1kOTdjNDRlMy02ZWMxLTQyYzEtODkwNi0xOTQ2NGY0NDFhNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTNUMDcxMjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNhNjRiMTU5NjM3YTJiYTQxNTk5YTgzYTUwMzI5NGQ3YWE5ZmYyNDYyZGVjZWZkMzE5MTdjNTFhMDVhYjY5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pEHdkn2QaSx3sS6gzMEubkmr6xy733j0feVZyUT33Xs)

I think I see your point. 
But the sample data from #6 is a gpx file with without any <time> attributes (the points given have no assigned time) nevertheless under "Layer Properties" > "Fields" in line 10 i see the type of capturte_time to be datetime instead of the string type I get using your master branch
![image](https://github.com/user-attachments/assets/c2fe2cf1-9ab7-4036-aea9-1e4c6305ed29)

I can reproduce the error you get using the "sample data". To this point in time I'm not entirely sure as to why it comes up. I will look into it and get back to you when I find a solution to this error appearing.

2025-01-13 16:21 UTC, SamMeuli commented
I just implemented your feedback. Now I can import the "sample data" successfully and the elevation and capture time are imported as their respective type.

2025-01-14 02:36 UTC, wondie requested changes

2025-01-14 02:36 UTC, wondie commented on importer/process_import.py
> +            field_value = float(
If it is too long, it is better and more readable to use multi-line statement according to PEP 8.  So it is better to use multi line, if `attribute_value_as_str is not None`. Also it is good to have the same condition in the first case for time.

2025-01-14 02:36 UTC, wondie commented on importer/process_import.py
> +
One empty line is enough

2025-01-16 06:53 UTC, SamMeuli commented
I implemented your changes. The if statements are changed from in-line to multi-line and the empty lines at the end of process_import.py are removed

2025-01-18 20:00 UTC, wondie requested changes

2025-01-18 20:00 UTC, wondie commented on importer/process_import.py
>              dt = QDateTime.fromString(attribute_value_as_str, Qt.ISODate)
What happens if attribute_value_as_str is None here? Could you put a check above this too for None?

2025-01-21 10:35 UTC, SamMeuli commented on importer/process_import.py
>              dt = QDateTime.fromString(attribute_value_as_str, Qt.ISODate)
`QDateTime.fromString(None, Qt.ISODate)` returns a `QDateTime` for which the method `isValid` returns `False`.
Therefore the `field_value` just gets assigned the value `None` (from `attribute_value_as_str`) in that case.

We presumably must set the field_type for all fields of the column consistently (which still allows for missing values encoded as `None`) even when some of the values are `None`. Therefore we must not include a check for `None` in the toplevel `if`, as that'd cause the `field_type` to fall back to `QVariant.String`.

2025-01-21 16:45 UTC, wondie commented on importer/process_import.py
>              dt = QDateTime.fromString(attribute_value_as_str, Qt.ISODate)
Perfect, I will approve it soon.

2025-01-23 01:17 UTC, merged

2025-01-23 02:38 UTC, wondie commented
@SamMeuli I have to revert it. The old version recognizes more evelation. See below:
![image](https://github.com/user-attachments/assets/665ce0a9-12d3-42dd-b1af-7031d2d2689d)

Your change
![image](https://github.com/user-attachments/assets/846e8f14-affc-4b5c-bb5d-585584872c06)

2025-01-23 17:30 UTC, wondie commented
@SamMeuli could you please connect with me on LinkedIn https://www.linkedin.com/in/wondim/ and send me your contact so that I can add you to Contributor list?